### PR TITLE
Upgrade to Unity 2017.1.0p4.

### PR DESCRIPTION
**Pull request by jasonlmassey**
made changes to the project to support unity editor 2017.1.0p4Update.  

Seems to work, this is the first time seeing this app.

### CODE REVIEW

**Comment by Feddas** [comment]
Awesome thanks. The only hesitance I have is that Unity 5.5.x supports Android 2.3, Unity 5.6, and beyond jump to version 4.1.  Very few people have Android OS's older than 4.1 now tho. I'll test this out later then merge :)

ref: https://forum.unity.com/threads/what-is-best-minimum-api-at-build-settings.416085/

**Comment by jasonlmassey** [comment]
np.  I just wanted to put it up there, just in case.  You can reject the MR
and maybe open an issue about upgrading to 2017.1.0p04 and i can point my
fork to that issue.  anything you need.  really cool app, i really
appreciate it.

**Comment by Feddas** [comment]
Thanks for checking out the project!
Just validated that the update you did works in Unity 2017.1.x. :-)

**Comment by jasonlmassey** [comment]
awesome...when your MR passes you are winning at life...

**Pull request merged**
